export const catData = [
    {
        id: 1,
        name: "Nova",
        age: "11 years",
        color: "Black",
        breed: "Domestic Shorthair",
        personality: "Playful and curious",
        description:
            "Nova is playful, curious, and always ready to explore. She loves chasing toys, climbing cat trees, and greeting everyone who visits the cafe.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_26_12%20PM.png",
        available: true,
    },
    {
        id: 2,
        name: "Evie",
        age: "7 years",
        color: "Brown and Black",
        breed: "Domestic Longhair",
        personality: "Calm and affectionate",
        description:
            "Evie is a laid-back girl who loves relaxing in sunny windows, being brushed, and enjoying a little catnip. She is happiest when she can curl up somewhere cozy.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_26_46%20PM.png",
        available: true,
    },
    {
        id: 3,
        name: "Binx",
        age: "5 years",
        color: "Black & White",
        breed: "Domestic Shorthair",
        personality: "Sweet and sassy",
        description:
            "Binx is the definition of a Sour Patch Kid, but in the best way. She is very passionate about her food, has plenty of personality, and is always ready to cuddle when the mood strikes.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_28_25%20PM.png",
        available: true,
    },
    {
        id: 4,
        name: "Cleo",
        age: "5 years",
        color: "Black & White",
        breed: "Tuxedo",
        personality: "Sweet and independent",
        description:
            "Cleo enjoys relaxing in cozy spots and doing her own thing, but when she is ready for attention, she will happily come over for pets and affection.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_29_23%20PM.png",
        available: false,
    },
    {
        id: 5,
        name: "Waffles",
        age: "3 years",
        color: "Orange Tabby",
        breed: "Domestic Shorthair",
        personality: "Goofy and outgoing",
        description:
            "Waffles is a goofy social butterfly who loves meeting new people. He is always ready to play and will do just about anything for a treat.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_30_31%20PM.png",
        available: true,
    },
    {
        id: 6,
        name: "Biscuit",
        age: "6 years",
        color: "White",
        breed: "Domestic Shorthair",
        personality: "Gentle and cuddly",
        description:
            "Biscuit is a gentle sweetheart who is happiest curled up beside someone. He loves chin scratches, quiet afternoons, and finding the coziest seat in the cafe.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_31_33%20PM.png",
        available: true,
    },
    {
        id: 7,
        name: "Theo",
        age: "8 months",
        color: "Gray Tabby",
        breed: "Domestic Shorthair",
        personality: "Playful and friendly",
        description:
            "Theo is a playful kitten who loves feather toys, cardboard boxes, and making new friends. His curious personality keeps him busy exploring everything around him.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_33_47%20PM.png",
        available: false,
    },
    {
        id: 8,
        name: "Hazel",
        age: "4 years",
        color: "Black, Orange & Cream",
        breed: "Tortoiseshell",
        personality: "Loyal and affectionate",
        description:
            "Hazel can be a little shy when she first meets someone, but once she trusts you, she becomes an affectionate companion who will happily follow you everywhere.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/ChatGPT%20Image%20Aug%2017,%202026,%2004_34_53%20PM.png",
        available: false,
    },
];