export const catData = [
    {
        id: 1,
        name: "Nova",
        age: "11 years",
        color: "Black",
        breed: "Domestic Shorthair",
        personality: ["Playful", "Curious", "Social"],
        goodWith: ["Children", "Adults"],
        description:
            "Nova is a curious, playful and energized cat. She loves toys, climbing cat trees, and greeting visitors as soon as they walk through the door.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Nova.png",
        available: true,
        gender: "Female",
        adoptionFee: 40,
        adoptionInfo:
            "Nova would do best in a home where she can get plenty of attention, cozy places to nap, and the occasional play session.",
    },
    {
        id: 2,
        name: "Evie",
        age: "7 years",
        color: "Brown & Black",
        breed: "Domestic Longhair",
        personality: ["Calm", "Affectionate", "Gentle"],
        goodWith: ["Dogs", "Adults"],
        description:
            "Evie is a calm and affectionate girl who loves sunny windows, being brushed, and relaxing with a little catnip.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Evie.png",
        available: true,
        gender: "Female",
        adoptionFee: 50,
        adoptionInfo:
            "Evie would thrive in a quieter home with plenty of comfortable places to lounge and someone who enjoys a cuddly companion.",
    },
    {
        id: 3,
        name: "Binx",
        age: "5 years",
        color: "Black & White",
        breed: "Domestic Shorthair",
        personality: ["Sweet", "Sassy", "Food-Motivated"],
        goodWith: ["Adults"],
        description:
            "Binx is the definition of a Sour Patch Kid — a little sassy one minute and incredibly sweet the next. She's food-motivated and loves cuddling when it's on her terms.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Binx.png",
        available: true,
        gender: "Female",
        adoptionFee: 60,
        adoptionInfo:
            "Binx is looking for a home that appreciates an independent cat with a big personality. Snacks are highly encouraged.",
    },
    {
        id: 4,
        name: "Cleo",
        age: "5 years",
        color: "Black & White",
        breed: "Tuxedo",
        personality: ["Sweet", "Independent", "Confident"],
        goodWith: ["Cats", "Adults"],
        description:
            "Cleo is a confident girl who enjoys affection but is equally happy doing her own thing. She loves finding quiet spots where she can watch everything happening around the café.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Cleo.png",
        available: false,
        gender: "Female",
        adoptionFee: 60,
        adoptionInfo:
            "Cleo has found her forever family and is no longer available for adoption.",
    },
    {
        id: 5,
        name: "Waffles",
        age: "3 years",
        color: "Orange Tabby",
        breed: "Domestic Shorthair",
        personality: ["Goofy", "Outgoing", "Playful"],
        goodWith: ["Cats", "Dogs", "Children"],
        description:
            "Waffles is a goofy social butterfly who loves meeting new people. He is always ready to play and will do just about anything for a treat.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Waffles.png",
        available: true,
        gender: "Male",
        adoptionFee: 60,
        adoptionInfo:
            "Waffles would love an active home with people or pets willing to play with him and include him in whatever they're doing.",
    },
    {
        id: 6,
        name: "Biscuit",
        age: "6 years",
        color: "White",
        breed: "Domestic Shorthair",
        personality: ["Gentle", "Cuddly", "Easygoing"],
        goodWith: ["Cats", "Children"],
        description:
            "Biscuit is a gentle cuddle bug who would happily spend an entire afternoon curled up beside you.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Biscuit.png",
        available: true,
        gender: "Male",
        adoptionFee: 50,
        adoptionInfo:
            "Biscuit would be a great match for someone looking for a relaxed companion who enjoys plenty of affection.",
    },
    {
        id: 7,
        name: "Theo",
        age: "8 months",
        color: "Gray Tabby",
        breed: "Domestic Shorthair",
        personality: ["Playful", "Friendly", "Energetic"],
        goodWith: ["Cats", "Dogs", "Children"],
        description:
            "Theo is a playful kitten who loves chasing toys, wrestling with his café friends, and exploring anything new.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Theo.png",
        available: false,
        gender: "Male",
        adoptionFee: 75,
        adoptionInfo:
            "Theo has found his forever home and is no longer available for adoption.",
    },
    {
        id: 8,
        name: "Hazel",
        age: "4 years",
        color: "Black, Orange & Cream",
        breed: "Tortoiseshell",
        personality: ["Loyal", "Affectionate", "Confident"],
        goodWith: ["Cats", "Adults"],
        description:
            "Hazel forms strong bonds with her favorite people and loves being nearby once she decides you're part of her inner circle.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Hazel.png",
        available: false,
        gender: "Female",
        adoptionFee: 60,
        adoptionInfo:
            "Hazel has found her forever family and is no longer available for adoption.",
    },
    {
        id: 9,
        name: "Murphy",
        age: "4 years",
        color: "Silver & Gray",
        breed: "Maine Coon",
        personality: ["Gentle", "Goofy", "Social"],
        goodWith: ["Cats", "Dogs", "Children"],
        description:
            "Murphy may look like a tiny lion, but he is a total softie. He loves following people around the café, chirping for attention, and finding the biggest spot on the couch.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Murphy.png",
        available: true,
        gender: "Male",
        adoptionFee: 80,
        adoptionInfo:
            "Murphy needs a home with plenty of space, regular grooming, and people who don't mind sharing their furniture with a very large cat.",
    },
    {
        id: 10,
        name: "Noodle",
        age: "2 years",
        color: "Cream & Gray",
        breed: "Munchkin",
        personality: ["Curious", "Playful", "Mischievous"],
        goodWith: ["Cats", "Children"],
        description:
            "Noodle has little legs and a huge personality. He loves chasing toys across the café, investigating bags, and sitting directly in the middle of whatever you are doing.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Noodle.png",
        available: true,
        gender: "Male",
        adoptionFee: 75,
        adoptionInfo:
            "Noodle would love an interactive home where he gets plenty of playtime, enrichment, and attention.",
    },
    {
        id: 11,
        name: "Luna",
        age: "5 years",
        color: "Cream with Seal Points",
        breed: "Siamese",
        personality: ["Talkative", "Affectionate", "Social"],
        goodWith: ["Cats", "Children"],
        description:
            "Luna always has something to say. She loves chatting with café guests, finding a warm lap, and making sure she is included in every conversation.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Luna.png",
        available: false,
        gender: "Female",
        adoptionFee: 60,
        adoptionInfo:
            "Luna has found her forever family and is no longer available for adoption.",
    },
    {
        id: 12,
        name: "Ziggy",
        age: "2 years",
        color: "Brown Rosetted",
        breed: "Bengal",
        personality: ["Energetic", "Mischievous", "Adventurous"],
        goodWith: ["Cats", "Dogs", "Adults"],
        description:
            "Ziggy treats the entire café like his personal playground. He loves climbing to the highest shelves, chasing toys, and finding creative ways to get everyone's attention.",
        imageId: "https://ik.imagekit.io/bbk3azqkom/Ziggy.png",
        available: false,
        gender: "Male",
        adoptionFee: 75,
        adoptionInfo:
            "Ziggy has found his forever family and is no longer available for adoption.",
    }
];