export const eventData = [
    {
        id: 1,
        title: "Cats & Coffee Morning",
        date: "Aug. 22, 2026",
        time: "9:00-11:00 AM",
        description: "Start your morning with coffee, pastries, and plenty of cat cuddles.",
        price: 12,
        spots: 15,
        category: "Social",
        imageId: "",
    },
    {
        id: 2,
        title: "Kitten Yoga",
        date: "Aug. 29, 2026",
        time: "10:00-11:00 AM",
        description: "A beginner-friendly yoga class with some of our most playful kittens roaming the room.",
        price: 20,
        spots: 12,
        category: "Wellness",
        imageId: "",
    },
    {
        id: 3,
        title: "Paint Your Pet Night",
        date: "Sept. 4, 2026",
        time: "6:30-8:30 PM",
        description: "Bring a favorite photo of your pet and create your own painted portrait. Supplies included.",
        price: 30,
        spots: 16,
        category: "Arts & Crafts",
        imageId: "",
    },
    {
        id: 4,
        title: "Purr & Pour Trivia Night",
        date: "Sept. 12, 2026",
        time: "7:00-9:00 PM",
        description: "Grab a team and test your knowledge with cat-themed and general trivia while hanging out with our adoptable cats.",
        price: 10,
        spots: 24,
        category: "Social",
        imageId: "",
    },
    {
        id: 5,
        title: "Saturday Adoption Party",
        date: "Sept. 19, 2026",
        time: "12:00-3:00 PM",
        description: "Meet our adoptable cats, talk with rescue volunteers, and maybe meet your new best friend.",
        price: "Free",
        spots: 30,
        category: "Adoption",
        imageId: "",
    },
    {
        id: 6,
        title: "Coffee & Cat Crochet Club",
        date: "Sept. 26, 2026",
        time: "10:00 AM-12:00 PM",
        description: "Bring your current crochet or knitting project for a cozy morning with coffee and cats.",
        price: 8,
        spots: 15,
        category: "Arts & Crafts",
        imageId: "",
    },
    {
        id: 7,
        title: "Black Cat Appreciation Night",
        date: "Oct. 2, 2026",
        time: "6:00-8:00 PM",
        description: "Celebrate our black cats with themed drinks, treats, photos, and adoption specials.",
        price: 10,
        spots: 20,
        category: "Special Event",
        imageId: "",
    },
    {
        id: 8,
        title: "Pumpkins & Purrs",
        date: "Oct. 10, 2026",
        time: "2:00-4:00 PM",
        description: "Paint a mini pumpkin while hanging out with the cats. Pumpkins and painting supplies are provided.",
        price: 18,
        spots: 18,
        category: "Seasonal",
        imageId: "",
    },
    {
        id: 9,
        title: "Cat Costume Halloween Party",
        date: "Oct. 24, 2026",
        time: "6:00-8:00 PM",
        description: "A Halloween party featuring costumes, themed drinks, games, and a cutest-costume contest.",
        price: 15,
        spots: 25,
        category: "Seasonal",
        imageId: "",
    },
    {
        id: 10,
        title: "Cat Café Book Club",
        date: "Nov. 7, 2026",
        time: "10:00 AM-12:00 PM",
        description: "Grab a coffee and join our monthly book discussion with a cat curled up nearby.",
        price: 8,
        spots: 15,
        category: "Social",
        imageId: "",
    },
    {
        id: 11,
        title: "Whiskers & Watercolors",
        date: "Nov. 14, 2026",
        time: "6:00-8:00 PM",
        description: "Spend the evening painting a cat-inspired watercolor while enjoying coffee and time with the café cats.",
        price: 22,
        spots: 16,
        category: "Arts & Crafts",
        imageId: "",
    },
    {
        id: 12,
        title: "Friendsgiving with the Cats",
        date: "Nov. 21, 2026",
        time: "5:00-7:00 PM",
        description: "Celebrate Friendsgiving with seasonal treats, cozy drinks, games, and plenty of cat cuddles.",
        price: 18,
        spots: 20,
        category: "Seasonal",
        imageId: "",
    },
    {
        id: 13,
        title: "Small Business Saturday: Shop & Snuggle",
        date: "Nov. 28, 2026",
        time: "10:00 AM-2:00 PM",
        description: "Shop local gifts and cat-themed goodies while spending time with our adoptable cats.",
        price: "Free",
        spots: 30,
        category: "Special Event",
        imageId: "",
    },
    {
        id: 14,
        title: "Holiday Wreath Workshop",
        date: "Dec. 5, 2026",
        time: "2:00-4:00 PM",
        description: "Create a festive holiday wreath while enjoying seasonal drinks and café cat company.",
        price: 30,
        spots: 15,
        category: "Arts & Crafts",
        imageId: "",
    },
    {
        id: 15,
        title: "Cookies & Cats",
        date: "Dec. 12, 2026",
        time: "1:00-3:00 PM",
        description: "Decorate holiday cookies, sip hot cocoa, and spend a cozy afternoon with the cats.",
        price: 18,
        spots: 20,
        category: "Seasonal",
        imageId: "",
    },
    {
        id: 16,
        title: "Holiday Cat Photo Day",
        date: "Dec. 19, 2026",
        time: "11:00 AM-3:00 PM",
        description: "Stop by for festive photos with the café cats in our holiday photo booth.",
        price: 10,
        spots: 25,
        category: "Seasonal",
        imageId: "",
    },
    {
        id: 17,
        title: "Pajamas & Purrs Movie Night",
        date: "Dec. 26, 2026",
        time: "6:00-8:30 PM",
        description: "Wear your coziest pajamas for a relaxing movie night with popcorn, hot chocolate, and cats.",
        price: 15,
        spots: 20,
        category: "Social",
        imageId: "",
    },
    {
        id: 18,
        title: "New Year's Eve Meow Mixer",
        date: "Dec. 31, 2026",
        time: "7:00-9:00 PM",
        description: "Celebrate the end of the year with mocktails, snacks, music, games, and your favorite café cats.",
        price: 22,
        spots: 25,
        category: "Special Event",
        imageId: "",
    },
    {
        id: 19,
        title: "New Year, New Meow Yoga",
        date: "Jan. 2, 2027",
        time: "10:00-11:00 AM",
        description: "Kick off the new year with a beginner-friendly yoga class surrounded by curious cats.",
        price: 20,
        spots: 12,
        category: "Wellness",
        imageId: "",
    },
    {
        id: 20,
        title: "Vision Boards & Whiskers",
        date: "Jan. 9, 2027",
        time: "2:00-4:00 PM",
        description: "Create a vision board for the new year while sipping coffee and hanging out with the cats.",
        price: 20,
        spots: 18,
        category: "Arts & Crafts",
        imageId: "",
    },
    {
        id: 21,
        title: "Coffee & Cat Crochet Club",
        date: "Jan. 16, 2027",
        time: "10:00 AM-12:00 PM",
        description: "Bring your crochet or knitting project for a cozy morning of crafting, coffee, and cats.",
        price: 8,
        spots: 15,
        category: "Arts & Crafts",
        imageId: "",
    },
    {
        id: 22,
        title: "Speed Dating: Cat Edition",
        date: "Jan. 23, 2027",
        time: "6:00-8:00 PM",
        description: "Looking for your perfect match? Spend a few minutes with each adoptable cat to discover which personality fits yours best.",
        price: 10,
        spots: 20,
        category: "Adoption",
        imageId: "",
    },
    {
        id: 23,
        title: "Cozy Mystery Book Club",
        date: "Jan. 30, 2027",
        time: "10:00 AM-12:00 PM",
        description: "Discuss the month's cozy mystery pick over coffee with plenty of feline company.",
        price: 8,
        spots: 15,
        category: "Social",
        imageId: "",
    },
]