export const menuData = [
    // ESPRESSO
    {
        id: 1,
        name: "Espresso",
        category: "Espresso",
        description: "A classic shot of espresso that is bold, smooth, and full of rich flavor.",
        price: 3.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/1_9fpe2fWKWN.png?updatedAt=1787098957467",
        available: true,
    },
    {
        id: 2,
        name: "Americano",
        category: "Espresso",
        description: "Espresso combined with hot water for a smooth and balanced coffee.",
        price: 3.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/2_U29CfJmqyu.png?updatedAt=1787098957156",
        available: true,
    },
    {
        id: 3,
        name: "Cappuccino",
        category: "Espresso",
        description: "Espresso topped with steamed milk and a thick layer of creamy foam.",
        price: 4.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/3_JJSSO7JMBt.png?updatedAt=1787098957380",
        available: true,
    },
    {
        id: 4,
        name: "Mocha",
        category: "Espresso",
        description: "Espresso mixed with chocolate and steamed milk, topped with whipped cream.",
        price: 5.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/4_0WT14qOY4-.png?updatedAt=1787098957101",
        available: true,
    },
    {
        id: 5,
        name: "Macchiato",
        category: "Espresso",
        description: "A bold shot of espresso finished with a small amount of steamed milk and foam.",
        price: 4.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/5_PJ4hQcFWj.png?updatedAt=1787098956957",
        available: true,
    },

    // LATTES
    {
        id: 6,
        name: "Vanilla Latte",
        category: "Latte",
        description: "Smooth espresso with steamed milk and sweet vanilla.",
        price: 5.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/6_gy2ShQREKq.png?updatedAt=1787098957461",
        available: true,
    },
    {
        id: 7,
        name: "Caramel Latte",
        category: "Latte",
        description: "Espresso and steamed milk with rich caramel for a sweet and creamy drink.",
        price: 5.25,
        imageId: "https://ik.imagekit.io/bbk3azqkom/7_xMcYRgitv7.png?updatedAt=1787098958137",
        available: true,
    },
    {
        id: 8,
        name: "Hazelnut Latte",
        category: "Latte",
        description: "A cozy combination of espresso, steamed milk, and nutty hazelnut.",
        price: 5.25,
        imageId: "https://ik.imagekit.io/bbk3azqkom/8_p96SdRQYW.png?updatedAt=1787098957981",
        available: true,
    },
    {
        id: 9,
        name: "Lavender Latte",
        category: "Latte",
        description: "Espresso and steamed milk with a lightly sweet and floral lavender flavor.",
        price: 5.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/9_iIIZMCwJtq.png?updatedAt=1787098957961",
        available: true,
    },
    {
        id: 10,
        name: "Maple Latte",
        category: "Latte",
        description: "Espresso and steamed milk sweetened with warm maple flavor.",
        price: 5.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/10_tS0PpMHHzM.png?updatedAt=1787098956949",
        available: true,
    },

    // TEA
    {
        id: 11,
        name: "Earl Grey",
        category: "Tea",
        description: "A classic black tea with smooth bergamot citrus notes.",
        price: 3.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/11_vMvyCVxGE7.png?updatedAt=1787098957636",
        available: true,
    },
    {
        id: 12,
        name: "Chamomile",
        category: "Tea",
        description: "A caffeine-free herbal tea with a gentle floral flavor.",
        price: 3.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/12_xfQcseke4g.png?updatedAt=1787098956944",
        available: true,
    },
    {
        id: 13,
        name: "Green Tea",
        category: "Tea",
        description: "A light and refreshing green tea with a smooth, delicate flavor.",
        price: 3.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/13_ZQkyIzTwuR.png?updatedAt=1787098957388",
        available: true,
    },
    {
        id: 14,
        name: "Peppermint Tea",
        category: "Tea",
        description: "A refreshing caffeine-free herbal tea with crisp peppermint flavor.",
        price: 3.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/14_HSA-0GNpil.png?updatedAt=1787098958384",
        available: true,
    },
    {
        id: 15,
        name: "Chai Tea",
        category: "Tea",
        description: "A warm black tea blended with cinnamon and aromatic spices.",
        price: 4.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/15_EtPPfLa7nw.png?updatedAt=1787098957026",
        available: true,
    },

    // PASTRIES
    {
        id: 16,
        name: "Butter Croissant",
        category: "Pastries",
        description: "A buttery, flaky croissant baked until perfectly golden.",
        price: 3.75,
        imageId: "https://ik.imagekit.io/bbk3azqkom/16_XguzoKA6Lj.png?updatedAt=1787098958426",
        available: true,
    },
    {
        id: 17,
        name: "Chocolate Croissant",
        category: "Pastries",
        description: "A flaky buttery croissant filled with rich chocolate.",
        price: 4.25,
        imageId: "https://ik.imagekit.io/bbk3azqkom/17_QyCfvUbqyu.png?updatedAt=1787098958430",
        available: true,
    },
    {
        id: 18,
        name: "Blueberry Muffin",
        category: "Pastries",
        description: "A soft bakery-style muffin filled with juicy blueberries and topped with a crumb topping.",
        price: 3.75,
        imageId: "https://ik.imagekit.io/bbk3azqkom/18_l1k5Ehygbw.png?updatedAt=1787098957969",
        available: true,
    },
    {
        id: 19,
        name: "Cinnamon Roll",
        category: "Pastries",
        description: "A warm cinnamon roll covered with sweet vanilla icing.",
        price: 4.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/19_TB3Z3j9ZFj.png?updatedAt=1787098958054",
        available: true,
    },
    {
        id: 20,
        name: "Chocolate Chip Cookie",
        category: "Pastries",
        description: "A soft-baked cookie loaded with chocolate chips.",
        price: 2.75,
        imageId: "https://ik.imagekit.io/bbk3azqkom/20_7fBsOLCdha.png?updatedAt=1787098958116",
        available: true,
    },

    // BREAKFAST
    {
        id: 21,
        name: "Avocado Toast",
        category: "Breakfast",
        description: "Toasted sourdough topped with smashed avocado, sea salt, and red pepper flakes.",
        price: 8.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/21.png?updatedAt=1787098958104",
        available: true,
    },
    {
        id: 22,
        name: "Greek Yogurt Parfait",
        category: "Breakfast",
        description: "Creamy Greek yogurt layered with granola, strawberries, and blueberries.",
        price: 7.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/22.png?updatedAt=1787098957457",
        available: true,
    },
    {
        id: 23,
        name: "Bagel with Cream Cheese",
        category: "Breakfast",
        description: "A toasted bagel served with a generous layer of cream cheese.",
        price: 5.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/1_9fpe2fWKWN.png?updatedAt=1787098957467",
        available: true,
    },
    {
        id: 24,
        name: "Breakfast Burrito",
        category: "Breakfast",
        description: "Scrambled eggs, cheese, potatoes, and vegetables wrapped in a warm flour tortilla.",
        price: 9.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/3_JJSSO7JMBt.png?updatedAt=1787098957380",
        available: true,
    },
    {
        id: 25,
        name: "Pancake Stack",
        category: "Breakfast",
        description: "A stack of fluffy pancakes topped with butter and maple syrup.",
        price: 8.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/25.png?updatedAt=1787098958409",
        available: true,
    },

    // LUNCH
    {
        id: 26,
        name: "Grilled Cheese",
        category: "Lunch",
        description: "Melted cheddar cheese grilled between slices of golden sourdough bread.",
        price: 8.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/26.png?updatedAt=1787098957174",
        available: true,
    },
    {
        id: 27,
        name: "Caprese Panini",
        category: "Lunch",
        description: "Fresh mozzarella, tomato, basil, and pesto pressed between toasted bread.",
        price: 10.00,
        imageId: "https://ik.imagekit.io/bbk3azqkom/27.png?updatedAt=1787098958456",
        available: true,
    },
    {
        id: 28,
        name: "Turkey Pesto Wrap",
        category: "Lunch",
        description: "Turkey, pesto, lettuce, tomato, and cheese wrapped in a soft flour tortilla.",
        price: 9.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/28.png?updatedAt=1787098957147",
        available: true,
    },
    {
        id: 29,
        name: "Cat Cafe Salad",
        category: "Lunch",
        description: "Mixed greens with cucumber, tomato, carrots, croutons, and your choice of dressing.",
        price: 8.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/29.png?updatedAt=1787098957556",
        available: true,
    },
    {
        id: 30,
        name: "Tomato Basil Soup",
        category: "Lunch",
        description: "Warm and creamy tomato soup finished with fresh basil.",
        price: 6.50,
        imageId: "https://ik.imagekit.io/bbk3azqkom/30.png?updatedAt=1787098957194",
        available: true,
    },
];